In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import random

In [2]:
# load data
df = pd.read_csv('student_shifts.csv')
df.head()

,S25,Unnamed: 1,MASTER 258/356,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94
0,NaN,NaN,WEEK 1,NaN,NaN,NaN,NaN,NaN,WEEK 2,NaN,...,NaN,WEEK 15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0
1,Date,NaN,Monday,Tuesday,Wednesday,Thursday,Friday,NaN,Monday,Tuesday,...,NaN,Monday,Tuesday,Wednesday,Thursday,Friday,NaN,NaN,NaN,NaN
2,NaN,NaN,5-May-25,6-May-25,7-May-25,8-May-25,9-May-25,NaN,12-May-25,13-May-25,...,NaN,11-Aug-25,12-Aug-25,13-Aug-25,14-Aug-25,15-Aug-25,NaN,NaN,NaN,NaN
3,Location,NaN,C105,C105,C105,C105,C105,NaN,C105,C105,...,NaN,C105,C105,C105,C105,C105,NaN,NaN,NaN,NaN
4,Time,NaN,9:00am - 1:00pm,9:00am - 1:00pm,9:00am - 1:00pm,9:00am - 1:00pm,9:00am - 1:00pm,NaN,9:00am - 1:00pm,9:00am - 1:00pm,...,NaN,9:00am - 1:00pm,9:00am - 1:00pm,9:00am - 1:00pm,9:00am - 1:00pm,9:00am - 1:00pm,NaN,NaN,NaN,NaN

In [3]:
# transpose
df_transposed = df.T
df_transposed.columns = [f'tcol_{i}' for i in range(df_transposed.shape[1])]
df_transposed.index = [i for i in range(df_transposed.shape[0])]
df_transposed = df_transposed[[f'tcol_{i}' for i in range(58)]]
df_transposed.head()

,tcol_0,tcol_1,tcol_2,tcol_3,tcol_4,tcol_5,tcol_6,tcol_7,tcol_8,tcol_9,...,tcol_48,tcol_49,tcol_50,tcol_51,tcol_52,tcol_53,tcol_54,tcol_55,tcol_56,tcol_57
0,NaN,Date,NaN,Location,Time,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,WEEK 1,Monday,5-May-25,C105,9:00am - 1:00pm,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Tuesday,6-May-25,C105,9:00am - 1:00pm,"Ameur, Mariem","Baskett, Charlotte","Bessette, Neve","Carreno Martinez, Maria Angelica","Chen, Wen Ti",...,"Ogiwara, Mayumi","Palmero Baptiste, Jahsenia","Park, Seojun","Sanita, Stephania","Subh, Raneem","Wong, Wan Sze","Yang, Kailin",NaN,NaN,NaN
4,NaN,Wednesday,7-May-25,C105,9:00am - 1:00pm,"Al-Juboori, Sarah","Baird, Jessica","Fan, Qingdian (Alan)","Feng, Nan (Kenna)","Ho, Yi-Ping (Nicole)",...,"Smith, Annice","To, Soi","Walser, Lauryn","Wang, Yuchen","Wu, Shu-Hui (Kate)","Cipagauta Rubiano, Sharon Yelitza",NaN,NaN,NaN,NaN

In [4]:
# set parsing scope
am_shift_index = [f'tcol_{i}' for i in range(5,34)]
pm_shift_index = [f'tcol_{i}' for i in range(38,58)]
# am_shift_index,pm_shift_index

In [5]:
# student names
student_list = ['Al-Juboori, Sarah', 'Baird, Jessica', 'Fan, Qingdian (Alan)', 
                'Feng, Nan (Kenna)', 'Ho, Yi-Ping (Nicole)', 'Karimpour, Masoud', 'Luo, Ziwen (Flora)', 'Salib, Monica', 'Sekhon, Harneesh', 'Sharpe, Mia', 'Smith, Annice', 'To, Soi', 'Walser, Lauryn', 'Wang, Yuchen ', 'Wu, Shu-Hui (Kate)']

In [6]:
date_list = []
diff_dict = {}
def get_day_shifts(df):
    date_str = df["tcol_2"]
    morning_shift = df[am_shift_index].copy()
    afternoon_shift = df[pm_shift_index].copy()
    morning_shift.dropna(inplace= True)
    morning_shift.reset_index(drop=True,inplace= True)
    afternoon_shift.dropna(inplace= True)
    afternoon_shift.reset_index(drop=True,inplace= True)
    return get_date_info(date_str), morning_shift , afternoon_shift
    
def get_different(list1,list2):
    return list(set(list1) - set(list2))

def get_date_info(date_str,date_format='%d-%b-%y'):
    date = pd.to_datetime(date_str, format=date_format)
    # day_of_week = date.day_name()
    # date.dayofweek
    return date

In [7]:
def get_week(df, num, is_debug = False):
    # print(f'Week {num}')
    num = num -1 
    start = 2 + num* 6
    end = 6 + num* 6 + 1
    df_week = df[start:end]
    for i in range(start,end):
        df_day = df_week.loc[i]
        date, morning_shift, afternoon_shift = get_day_shifts(df_day)
        if date.dayofweek in [2,4]:
            am_list = morning_shift.to_list()
            pm_list = afternoon_shift.to_list()
            am_dif_list = get_different(student_list,am_list)
            pm_dif_list = get_different(student_list,pm_list)
            date_list.append(date)
            date_str = date.strftime("%Y-%m-%d")
            if len(am_dif_list) != 0 and len(am_dif_list) < 15:
                if is_debug:
                    print(f"\n{date_str}_AM_DIFF({len(am_dif_list)})\n",am_dif_list)
                diff_dict[f'{date_str}_am'] = am_dif_list
            if len(pm_dif_list) != 0 and len(pm_dif_list) < 15 and is_debug:
                if is_debug:
                    print(f"\n{date_str}_PM_DIFF({len(pm_dif_list)})\n",pm_dif_list)
                diff_dict[f'{date_str}_pm'] = pm_dif_list
            if len(am_dif_list) >= len(student_list) or len(pm_dif_list) >= len(student_list):
                date_list.remove(date)

In [8]:
# Parsing 15 weeks
date_list = []
diff_dict = {}
for w in range(1,16):
    get_week(df_transposed,w)
# datetime[] to str[]
str_date_list = [ts.strftime("%Y-%m-%d") for ts in date_list]

In [9]:
# initializing schedule and calculate counts
cleaner_text = "Cleaner"
receptionist_text = "Receptionist"
c_assignment_count = {s: 0 for s in student_list}
r_assignment_count = {s: 0 for s in student_list}
scheduler = {}

In [10]:
def schedule_shift(key, is_rand = False):
    scheduler[key] = {}
    available_students = [s for s in student_list if s not in diff_dict.get(key, [])]
    if is_rand:
        random.shuffle(available_students)
    # pick clearner 
    cleaner = min(available_students, key=lambda s: c_assignment_count[s])
    c_assignment_count[cleaner] += 1
    scheduler[key][cleaner_text] = cleaner
    available_students.remove(cleaner)  # prevent the same clearner and receptionist
    
    # pick receptionist
    receptionist = min(available_students, key=lambda s: r_assignment_count[s])
    r_assignment_count[receptionist] += 1
    scheduler[key][receptionist_text] = receptionist

In [11]:
#schedule_shifts 
c_assignment_count = {s: 0 for s in student_list}
r_assignment_count = {s: 0 for s in student_list}
scheduler = {}
rand=True
suffix = "random" if rand else "fix"
for date_str in str_date_list:
    key = f'{date_str}_am' 
    schedule_shift(key)
    key = f'{date_str}_pm' 
    schedule_shift(key,is_rand=rand)

In [12]:
# validation
c = 0
error = 0
for key in scheduler:
    if key in diff_dict:
        c += 1
        duplicate_students = [s for s in scheduler[key] if s in diff_dict.get(key, [])]
        if(len(duplicate_students)!=0):
            error += 1
            print("Error:",key)
# print(error,c)
if error == 0:
    print("No error!")
else:
    print("Error occured, please recheck again!")
    # c_assignment_count = {s: 0 for s in student_list}
    # r_assignment_count = {s: 0 for s in student_list}
    # scheduler = {}

No error!

In [13]:
df_scheduler = pd.DataFrame.from_dict(scheduler, orient='index')
df_scheduler.reset_index(inplace=True)
df_scheduler.rename(columns={'index': 'shift'}, inplace=True)
df_scheduler.head()

           shift               Cleaner          Receptionist
0  2025-05-07_am     Al-Juboori, Sarah        Baird, Jessica
1  2025-05-07_pm     Karimpour, Masoud     Al-Juboori, Sarah
2  2025-05-09_am        Baird, Jessica  Fan, Qingdian (Alan)
3  2025-05-09_pm  Ho, Yi-Ping (Nicole)         Smith, Annice
4  2025-05-14_am  Fan, Qingdian (Alan)     Feng, Nan (Kenna)

In [14]:
# save to file
df_scheduler.to_csv(f"tcm_student_shifts_{suffix}.csv")

In [15]:
# generate the count report and save to a csv[optional]
data = []
data.append({
        '': "",
        'Cleaner Count': "Cleaner Count",
        'Receptionist Count': "Receptionist Count"
    })
for student in student_list:
    data.append({
        '': student,
        'Cleaner Count': c_assignment_count.get(student, 0),
        'Receptionist Count': r_assignment_count.get(student, 0)
    })

df_count = pd.DataFrame(data)
df_count_t = df_count.T
df_count_t.reset_index(drop=True,inplace= True)
df_count_t.columns = ["shift"]+student_list
df_count_t.head()

,shift,"Al-Juboori, Sarah","Baird, Jessica","Fan, Qingdian (Alan)","Feng, Nan (Kenna)","Ho, Yi-Ping (Nicole)","Karimpour, Masoud","Luo, Ziwen (Flora)","Salib, Monica","Sekhon, Harneesh","Sharpe, Mia","Smith, Annice","To, Soi","Walser, Lauryn","Wang, Yuchen","Wu, Shu-Hui (Kate)"
0,,"Al-Juboori, Sarah","Baird, Jessica","Fan, Qingdian (Alan)","Feng, Nan (Kenna)","Ho, Yi-Ping (Nicole)","Karimpour, Masoud","Luo, Ziwen (Flora)","Salib, Monica","Sekhon, Harneesh","Sharpe, Mia","Smith, Annice","To, Soi","Walser, Lauryn","Wang, Yuchen","Wu, Shu-Hui (Kate)"
1,Cleaner Count,4,4,4,4,4,4,4,3,4,3,3,4,3,4,4
2,Receptionist Count,4,4,3,4,4,4,4,3,4,4,3,4,4,4,3

In [16]:
# export report csv by merging counts and schedule
for key in scheduler:
    obj = scheduler[key]
    cleaner = obj[cleaner_text]
    receptionist = obj[receptionist_text]
    # new_row_dict = {s: "" for s in student_list}
    diff_list = diff_dict.get(key,[])
    new_row_dict = {s: "Cleaner" if s == cleaner else "Receptionist" if s == receptionist else "W.S" if s in diff_list else ""
    for s in student_list}
    new_row_dict["shift"] = key
    new_row = pd.DataFrame([new_row_dict])
    df_count_t = pd.concat([df_count_t, new_row], ignore_index=False)
df_count_t.reset_index(drop=True,inplace= True)
df_count_t.to_csv(f"tcm_student_total_shifts_{suffix}.csv")

In [17]:
df_count_t[3:10]

,shift,"Al-Juboori, Sarah","Baird, Jessica","Fan, Qingdian (Alan)","Feng, Nan (Kenna)","Ho, Yi-Ping (Nicole)","Karimpour, Masoud","Luo, Ziwen (Flora)","Salib, Monica","Sekhon, Harneesh","Sharpe, Mia","Smith, Annice","To, Soi","Walser, Lauryn","Wang, Yuchen","Wu, Shu-Hui (Kate)"
3,2025-05-07_am,Cleaner,Receptionist,,,,,,,,,,,,,
4,2025-05-07_pm,Receptionist,,,,,Cleaner,,,,,,,,,
5,2025-05-09_am,,Cleaner,Receptionist,,,,,,,,,,,,
6,2025-05-09_pm,,,,,Cleaner,,,,,,Receptionist,,,,
7,2025-05-14_am,,,Cleaner,Receptionist,,,,,,,,,,,
8,2025-05-14_pm,,,,Cleaner,,,,,,,,Receptionist,,,
9,2025-05-16_am,,,,,Receptionist,,Cleaner,,,,,,,,